# SMTP Configuration
smtp.host= smtp-mail.outlook.com
smtp.port= 587
smtp.username= azeemk@clarium.tech
smtp.password = hmpyrxclqshxkncy

# Email Details
email.from=azeemk@clarium.tech
email.to=gokuls@clarium.tech,azeemk@clarium.tech
email.cc=MohanapriyaM@clarium.tech
email.subject= Test Execution Report Docs